### ISSUE TITLE
第三题有点问题

### ISSUE THREAD

**Issue by q98w** [jinshangheng/bupt_ds_exercise#1]
随手写了个1+2*(2*2)+1测试了一下没过，似乎是括号内外不能连乘？

**Comment by jinshangheng** [comment]
这段代码在北邮OJ上通过了。我在我的环境下(clang version 11.0.0)也试验了你所说的这段代码，未报错且输出结果正确。同时我也测验了其他括号外连乘的情况，均无输出错误。初步考虑是因编译环境不同，或括号、运算符等字符编码方式异常导致。
